2019-01-03 05:46:21.984889: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-01-03 05:46:23.022240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:d8:00.0
totalMemory: 11.90GiB freeMemory: 260.44MiB
2019-01-03 05:46:23.022369: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-03 05:46:23.493550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-03 05:46:23.493606: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-01-03 05:46:23.493614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-01-03 05:46:23.493839: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 196 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:d8:00.0, compute capability: 6.1)
2019-01-03 05:46:23.511536: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 196.44M (205979648 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-01-03 05:46:23.642019: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-01-03 05:46:23.644639: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Using TensorFlow backend.
Traceback (most recent call last):
  File "run.py", line 150, in <module>
    model._set_inputs(dummy_x)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 1246, in _set_inputs
    self._eager_set_inputs(inputs)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/training/checkpointable/base.py", line 474, in _method_wrapper
    method(self, *args, **kwargs)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 1274, in _eager_set_inputs
    dummy_output_values = self.call(dummy_input_values)
  File "/home/yash/exp/kp/P-adam/vgg16-net/model.py", line 53, in call
    prev_out = layer(prev_out)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/keras/layers/convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 871, in __call__
    return self.conv_op(inp, filter)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 521, in __call__
    return self.call(inp, filter)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 205, in __call__
    name=self.name)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 982, in conv2d
    name=name, ctx=_ctx)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1022, in conv2d_eager_fallback
    ctx=_ctx, name=name)
  File "/home/yash/p3_ternsorflow/lib/python3.5/site-packages/tensorflow/python/eager/execute.py", line 66, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]
